{% set name = "COMPAS" %}
{% set version = "0.15.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4452f10b9bacf2dbab6ebe17c6073166c47b76cec03a613c0d04e18b47d72975

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - binaryornot
    - cython
    - ezdxf
    - python
    - matplotlib-base >=2.2,<3.0  # [py2k]
    - matplotlib-base >=2.2,<3.1  # [win and not py2k]
    - matplotlib-base >=2.2  # [not win and not py2k]
    - networkx
    - numba
    - numpy >=1.15
    - pillow
    - python-planarity
    - scipy >=1.1
    - sympy
    - xorg-libxext           # [linux and py27]

test:
  imports:
    - compas
    - compas_blender
    - compas_ghpython
    - compas_rhino

about:
  home: http://compas-dev.github.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: The COMPAS framework
  description: |
    COMPAS is an open-source, Python-based computational framework
    for collaboration and research in architecture, engineering and
    digital fabrication. It is developed by the Block Research
    Group (https://block.arch.ethz.ch) of ETH Zurich (http://www.ethz.ch),
    with the support of the National Centre for Competence in
    Research on "Digital Fabrication" (http://www.dfab.ch).
  doc_url: https://compas-dev.github.io
  dev_url: https://github.com/compas-dev/compas

extra:
  recipe-maintainers:
    - brgcode
    - gonzalocasas
