appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jgO8ifCsTdV226UP8eCL4XFcj2zTDfxmkheNLs1b0ruu3G4EcSx07v2XsZLQAGIU+BP5zt8wMjZzOivSK9R91/PITFLDGp9WoOL2u+m/apRIndPnBBqPH6l2uHstnx+LMigr9TmfeiVBLlecN5wpmqhMwvEfpCtuRiq0FTkiIjZ2euz+A3nrvCze2KzBhLNcI2zoMPsKUvrM69dyzeBTlETGSW8U0/dXogCqUztfuKdtK2hPJAt32UAbrnHm0pxkV2vYbRhp7HJ0zN5rNxrw8X8lsI1FQ4L6/ewvaggG1zp74lPMgaGgZx7m8XaBOSLWviWzw+4eXcf+v7pLKYkMfj7Aw9P7QbsdJ9Q+qHPkZ6A8w9cnLx5aqbP6WWBHc57RU1JvDwCRfuYJkT6yPQwgM2mOlhLT3r16latou2hVIzfyuMGRDFcT+8uOfDZHbNnVb7kkIgmthe5wSRDEdpAmFIXKIBPhGRNsQ7pgYGVOtbz4d697HJqlXttykHHjLzTgS6SEffcttVUC245NNYuVQV++jA+Q2BJV/Cc5xrzIpFCAmvGI9O4d4b2D/nvfZZCRVQzJSWiNN+XCMnF1hjdeA5RczMp7Y9rz3XY+woBKiy8ryB8QOxy3Af2MpbyX+zCayNn7P4YY0gyhIfq5tcmudR6im6lCeMnswSB9WutHzpA=}
provider:
  win: azure
