travis:
  secure:
    BINSTAR_TOKEN: bZdbmsiQ6Th6WZrM5ACAz3rLQ/u5AqOv0YH/Gat4pkMR/Ie1dQpP6R8gkUKS01hpZTEV9u1c0IcpYmTRI1+m/NOhfjZDRDAdJ2a4LlXGeFpw2c10Zoopyt3ITa4jD5wqczw/ocFUpA2+gdXSDKHycVnzTbAEEp3UEAo24y4Jqhm9UjiwSdh0TH2VnkCu1RWcsVOsAz3vuZLusYUiSbbEHkEhoK8LyNg1pnbRdYd85NQEDOW6AsIHUbTXiSGii537tqPkWJKEy7I/SbBfAkv+8kFQFGJF2mM3JXQq/xbIZ7h18QqhZOTMFsnP6wBg9hJNUfu2Q6U2QPDqb2Ps5gGV2Pj5ZnB4zX3VxtrGhOZecAu0aWP4tlOXrqJC+bJmyzF0CuAAynHomkAuxxcE9G85kXxCcE9W4woMdwPZaXZjm5ovSRaGr62iZZXOc7agPDioEtFJ1qDLSTIFXH7BgGPz9Re1nKCk4bTmdUhNiS+7WEn54ccst9/lS/BuH6yTOVKw2XzQyb8NMxE+CkHJMZ+smIKRQdfvm9WFEUrZrK12y4WHAcq1dPG5x/2Mb080SIwF55lzrI8V3oyXtJPdvJjn+aH/OFBeNKetJ09NAOFFcsIg5PYoh0XBj0Hs7gxrm3Dcz6yB3vvu2IUisWbOXcIlVHTN9lot7Fpu9cfnfTuVpKc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
